### ISSUE TITLE
[bug] 'attempt to subtract with overflow' when extracting last chunk from with `nth`

### ISSUE THREAD

**Issue by jmmaloney4** [bitvecto-rs/bitvec#142]
I have this program:

```rust
let a: u64 = 1581109321816487388;
println!("{}", a.view_bits::<Msb0>().chunks(6).nth(10).unwrap());
```

`a` is a `u64` so there should be 10 chunks of 6 bits, and a remaining 11th chunk of 4 bits. So extracting `nth(10)` should yield this last chunk of 4 bits. However I get this error instead:

```
thread 'main' panicked at 'attempt to subtract with overflow', /Users/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/bitvec-0.22.3/src/slice/api.rs:2653:58
stack backtrace:
   0: rust_begin_unwind
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:101:14
   2: core::panicking::panic
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:50:5
   3: <core::ops::range::RangeFrom<usize> as bitvec::slice::api::BitSliceIndex<O,T>>::get_unchecked::{{closure}}
             at /Users/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/bitvec-0.22.3/src/slice/api.rs:2653:52
   4: <core::ops::range::RangeFrom<usize> as bitvec::slice::api::BitSliceIndex<O,T>>::get_unchecked
             at /Users/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/bitvec-0.22.3/src/slice/api.rs:2604:5
   5: bitvec::slice::api::<impl bitvec::slice::BitSlice<O,T>>::get_unchecked
             at /Users/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/bitvec-0.22.3/src/slice/api.rs:470:3
   6: bitvec::slice::BitSlice<O,T>::split_at_unchecked
             at /Users/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/bitvec-0.22.3/src/slice.rs:1986:32
   7: <bitvec::slice::iter::Chunks<O,T> as core::iter::traits::iterator::Iterator>::nth
             at /Users/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/bitvec-0.22.3/src/slice/iter.rs:917:4
... Code in my program calling `nth`
```
Using `nth` for all other chunks works as expected without errors.

And if I run this instead:

```rust
let a: u64 = 1581109321816487388;
a.view_bits::<Msb0>().chunks(6).for_each(|c| {
    println!("{}", c);
});
```

I enounter no errors, and all bits are printed out correctly, including the remainder chunk:
```
[000101]
[011111]
[000100]
[111010]
[100011]
[010001]
[010111]
[101110]
[001101]
[011101]
[1100]
```

So I think this may have something to do with an optimization made in the `nth` call.

There is also a problem with the `nth` call to `chunks_exact` but it is slightly different:

```rust
let a: u64 = 1581109321816487388;
println!("{:?}", a.view_bits::<Msb0>().chunks_exact(6).nth(9));
```
Yields:
```
None
```
But should instead yield the last full chunk. There are 10 of them, so index 9 is in range and the last. Again running:

```rust
let a: u64 = 1581109321816487388;
a.view_bits::<Msb0>().chunks_exact(6).for_each(|c| {
    println!("{}", c);
});
```

Yields:

```
[000101]
[011111]
[000100]
[111010]
[100011]
[010001]
[010111]
[101110]
[001101]
[011101]
```

Which is all 10 full chunks as expected, and `.remainder()` yields the correct remainder chunk. It is just calling `nth` with the last index in the iterator that causes issues.

**Comment by jmmaloney4** [comment]
Maybe worth noting that this is on an M1 mac. I haven't tried this on another platform.

**Comment by myrrlyn** [comment]
This is a bug in my transcription of `core::slice::ChunksExact::nth`. Thank you for the report; I'll review the other iterators and issue a patch.

**Comment by myrrlyn** [comment]
This issue is resolved in the v1 release candidate, so I am closing this. I have added it to my 0.22 milestone for a patch after it releases. Thank you for your patience; please feel free to re-open if I do not have a patch later in the month.
